# Generated by Django 3.0.4 on 2020-04-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20200424_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='Без категорий', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.Category', verbose_name='Category'),
        ),
    ]
